trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo $(Build.SourcesDirectory)
    
  displayName: 'Run a one-line script'

- checkout: self
  displayName: 'Checkout repository'

- script: |
    # Use the Build.Repository.LocalPath variable to get the repository path
    echo "Repository Path: $(Build.Repository.LocalPath)"
    # You can now use this path for your build and test actions
    cd $(Build.Repository.LocalPath)
    ls
    # Add your build and test commands here
  displayName: 'Build and test'
